name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v3
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        lfs: true
    - name: Git Sumbodule Update
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Restore NuGet Packages
      run: |
        nuget restore FlashingTool.sln
    - name: Build
      run: msbuild FlashingTool.sln /p:Configuration=Release /p:platform=x86
    - name: upload
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: Rtest
        # A file, directory or wildcard pattern that describes what to upload
        path: FlashingTool\bin\output\*.*
